const express = require('express');
const router = express.Router();

// POST /api/email/send
// Since we don't have SMTP configured, we return the email content
// for the frontend to open in default email client via mailto:
router.post('/send', (req, res) => {
  const { to, subject, body, plan } = req.body;
  if (!plan) return res.status(400).json({ error: 'No plan data provided' });

  // Format plan as text
  let emailBody = `📚 My NeuralPrep Study Plan\n${'='.repeat(40)}\n\n`;
  emailBody += `Generated: ${new Date().toLocaleDateString()}\n`;
  emailBody += `Mode: ${plan.config?.examMode?.toUpperCase() || 'SEMESTER'}\n\n`;
  emailBody += `PREDICTED SCORES:\n${'-'.repeat(30)}\n`;

  plan.predictions?.forEach(p => {
    const pct = Math.round((p.predicted / p.maxMark) * 100);
    const status = pct >= 75 ? '✅ EXCELLENT' : pct >= 45 ? '🟠 AVERAGE' : '🚨 CRITICAL';
    emailBody += `• ${p.subject}: ${p.predicted}/${p.maxMark} (${pct}%) — ${status}\n`;
  });

  emailBody += `\nGENERATED BY NeuralPrep — Smart Exam Scheduler\n`;
  emailBody += `Visit: https://neural-prep.onrender.com\n`;

  // Return formatted content for mailto link
  return res.json({
    success: true,
    mailtoLink: `mailto:${to || ''}?subject=${encodeURIComponent(subject || 'My NeuralPrep Study Plan')}&body=${encodeURIComponent(emailBody)}`,
    emailBody
  });
});

module.exports = router;
